version: "3"

services:
    inspect:
        build:
            context: ./inspect
        tty: true
    web:
        build:
            context: ./web
        volumes:
            - ./web/html:/usr/share/nginx/html